#Author: Johannes Wimmer, Lukas Pietzschmann, Vincent Ugrai

version: "3.9"
services:
    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        networks:
            - crushit
        ports:
            - "80:3000"
        restart: unless-stopped

    wikihow:
        build:
            context: backend
            dockerfile: ./services/WikiHow Service/Dockerfile
        networks:
            - crushit
        restart: unless-stopped

    training:
        build:
            context: backend
            dockerfile: ./services/Training Service/Dockerfile
        networks:
            - crushit
        restart: unless-stopped

    eventpublisher:
        build:
            context: backend
            dockerfile: ./services/EventPublisher/Dockerfile
        networks:
            - crushit
        restart: unless-stopped

    accountservice:
        build:
            context: backend
            dockerfile: ./services/Account Service/Dockerfile
        networks:
            - crushit
        restart: unless-stopped
    proxy:
        build:
            context: backend/
            dockerfile: ./proxy/Dockerfile
        networks:
            - crushit
        ports:
            - "5000:5000"
        restart: unless-stopped
networks:
    crushit:
        driver: bridge