#Author: Johannes Wimmer, Lukas Pietzschmann, Vincent Ugrai

version: "3.9"
services:
    frontend:
        image: fitnessappcontainerregistry.azurecr.io/crushit:frontend
        build:
            context: ./frontend
            dockerfile: Dockerfile
        networks:
            - crushit
        ports:
            - "80:3000"
        restart: unless-stopped

    wikihow:
        image: fitnessappcontainerregistry.azurecr.io/crushit:backend-wikihow
        build:
            context: ./backend
            dockerfile: ./services/WikiHow Service/Dockerfile
        networks:
            - crushit
        restart: unless-stopped

    training:
        image: fitnessappcontainerregistry.azurecr.io/crushit:backend-training
        build:
            context: ./backend
            dockerfile: ./services/Training Service/Dockerfile
        networks:
            - crushit
        restart: unless-stopped

    shopping:
        image: fitnessappcontainerregistry.azurecr.io/crushit:backend-shopping
        build:
            context: ./backend
            dockerfile: ./services/Shopping Service/Dockerfile
        networks:
            - crushit
        restart: unless-stopped

    eventpublisher:
        image: fitnessappcontainerregistry.azurecr.io/crushit:backend-eventpublisher
        build:
            context: ./backend
            dockerfile: ./services/EventPublisher/Dockerfile
        ports:
            - "4000:4000"
        networks:
            - crushit
        restart: unless-stopped

    accountservice:
        image: fitnessappcontainerregistry.azurecr.io/crushit:backend-account
        build:
            context: ./backend
            dockerfile: ./services/Account Service/Dockerfile
        networks:
            - crushit
        restart: unless-stopped
    proxy:
        image: fitnessappcontainerregistry.azurecr.io/crushit:backend-proxy
        build:
            context: ./backend
            dockerfile: ./proxy/Dockerfile
        networks:
            - crushit
        ports:
            - "5000:5000"
        restart: unless-stopped
networks:
    crushit:
        driver: bridge